### ISSUE TITLE
Susy declaration for full width content

### ISSUE THREAD

**Issue by mafsdisseny** [joshmedeski/rootbeer#5]
Hi Josh,
Just looking for a susy integration for genesis, and rootbeer really rocks!
Great job and thanks for sharing!

I think that there's a typo in the susy grid declaration for full-width-content, you declare it as:
`.full-width-content .content { @include span(8 of 12); @include push(2 of 12); }`
And I guess you wanted to write it as follows:
`.full-width-content .content { @include span(12 of 12); }`
Isn't it?

Nothing else, I hope you find it useful!

**Comment by joshmedeski** [comment]
Thanks for sharing Miguel!

The problem with 12 columns as the full-width is the text becomes too long. It's better to keep the full-width content thinner and remove the sidebar, so I decided to make it 8 columns wide and push it a little to make it centered.

I hope I explained it clearly. If you prefer the full 12 columns feel free to fork it and make it your own!

**Comment by mafsdisseny** [comment]
OK, understood! Now it makes sense :)
